# Generated by Django 3.1.2 on 2020-12-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Заголовок новости', max_length=80, verbose_name='Заголовок новости')),
                ('text', models.TextField(help_text='Текст новости', verbose_name='Текст новости')),
                ('image', models.ImageField(blank=True, help_text='Фото', null=True, upload_to='', verbose_name='Фото')),
                ('time', models.DateTimeField(help_text='Дата и время публикации', verbose_name='Дата и время публикации')),
            ],
        ),
    ]
