# Generated by Django 3.1.2 on 2021-01-08 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.TextField(blank=True, help_text='Фото', null=True, verbose_name='Фото'),
        ),
    ]
